---
- hosts: Fedora
  remote_user: fedora
  become: yes
  become_method: sudo

  tasks:

  - name: Install dnf-plugins-core
    dnf: 
      name: dnf-plugins-core
      state: latest     

  - name: Add docker repo
    shell:  'dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo'

  - name: Install docker-ce
    dnf: 
      name: docker-ce
      state: latest

  - name: Install docker-ce-cli
    dnf: 
      name: docker-ce-cli
      state: latest

  - name: Install containerd.io
    dnf: 
      name: containerd.io
      state: latest

  - name: Install docker-compose
    dnf: 
      name: docker-compose
      state: latest

  - name: Start docker service
    systemd:
      state: started
      name: docker

  - name: enable Docker services
    service:
      name: "docker"
      state: started
      enabled: yes
    register: service_output

  - name: Docker service status
    debug: 
      var: service_output