#!/usr/bin/env bash

sudo apt-get update
sudo apt-get install -y apt-transport-https ca-certificates curl git-core software-properties-common
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add 
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update
sudo apt-get install -y docker-ce docker-compose
sudo systemctl start docker
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

sudo chmod +x /usr/local/bin/docker-compose

sudo mkdir /var/docker
sudo git clone https://github.com/MrRahmat/react-nodejs-rest-docker /var/docker/ls-lab3

cd /var/docker/ls-lab3
sudo docker-compose build
sudo docker-compose up
